# Generated by Django 4.1 on 2022-09-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
