# Generated by Django 4.1 on 2022-08-24 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_team',
            new_name='is_staff',
        ),
    ]
