# Generated by Django 4.1 on 2022-09-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
